export enum ScalingStat {
  flatAttack = 'Attack',
  flatDefense = 'Defense',
  flatHP = 'HP',
  attackPercent = 'Attack%',
  defensePercent = 'Defense%',
  hpPercent = 'HP%',
  taunt = 'Taunt',
  speed = 'Speed',
  critDamage = 'Crit DMG',
  critRate = 'Crit Rate',
  effectHitRate = 'Effect Hit Rate',
  healingBoost = 'Healing Boost',
  breakEffect = 'Break Effect',
  energyRegen = 'Energy Regen%',
  physicalDamage = 'Physical DMG%',
  fireDamage = 'Fire DMG%',
  iceDamage = 'Ice DMG%',
  windDamage = 'Wind DMG%',
  lightningDamage = 'Lightning DMG%',
  quantumDamage = 'Quantum DMG%',
  imaginaryDamage = 'Imaginary DMG%'
}